# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: CIpipeline
  jobs:
  - job: BuildNPublish
    steps:
    - task: CmdLine@2
      inputs:
        script: 'sh arm.sh'
    - task: CmdLine@2
      inputs:
        script: 'pwd ls'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '.'
        Contents: '*.txt'
        TargetFolder: '$(build.artifactsstagingdirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactsstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: '07c95003-8ac1-41f0-a09e-cf6e7bd4a1e6/58821c68-5826-4da3-8af9-9e0df9e38c28'
        vstsFeedPackagePublish: '*'
        versionOption: 'custom'
        versionPublish: '1.0'
    
    
