# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: CIpipeline
  jobs:
  - job: BuildNPublish
    steps:
    - task: CmdLine@2
      inputs:
        script: 'sh arm.sh'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '.'
        Contents: '*.txt'
        TargetFolder: '$(build.artifactsstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

