# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: CIpipeline
  jobs:
  - job: BuildNPublish
    steps:
    - task: CmdLine@2
      inputs:
        script: 'sh arm.sh'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '.'
        Contents: '*.txt'
        TargetFolder: '$(build.artifactsstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactsstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial(82da41e7-dfc6-4822-87b9-bd64c2752347)'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: '$(System.DefaultWorkingDirectory)'
    
    
